### ISSUE TITLE
How to get sunrise in Java SDK

### ISSUE THREAD

**Issue by Wemaka** [open-meteo/sdk#100]
I'm doing a flatFormat query.
I have the sunrise time stored in unix format.

`VariableWithValues sunrise = new VariablesSearch(daily).variable(Variable.sunrise).first();
System.out.println(sunrise.values(0));`
I'm getting 0.0

This is what the response looks like in json format.
`"daily": {
    ...
    "sunrise": [
      1715218156,
      1715304438,
      1715390723
    ],
    "sunset": [
      1715275415,
      1715361928,
      1715448440
    ]
  }`

How do I get a normal sunrise time in java ?

**Comment by patrick-zippenfenig** [comment]
Hi, sunrise and sunset are encoded as 64 bit integers in the `ValuesInt64` attribute. See here: https://github.com/open-meteo/python-requests/issues/44
