### ISSUE TITLE
Failed to resolve flat buffers dependency for SPM 

### ISSUE THREAD

**Issue by timroering** [open-meteo/sdk#145]
Every time I try to add the SDK to the project, it fails to get the flatbuffers dependency.

<img width="1052" alt="Bildschirmfoto 2024-10-03 um 11 39 59" src="https://github.com/user-attachments/assets/f70561c0-7bf1-4a4c-8e66-c0c9533ebec4">

**Comment by patrick-zippenfenig** [comment]
Strange. Can you add `.package(url: "https://github.com/google/flatbuffers.git", from: "24.3.25"),` to your dependencies manually?

**Comment by timroering** [comment]
Tried it but same result. 
<img width="1052" alt="Bildschirmfoto 2024-10-03 um 11 39 59" src="https://github.com/user-attachments/assets/c2d03e51-ce54-403b-af09-2812f9f67161">

**Comment by patrick-zippenfenig** [comment]
`24.3.25` is the latest and correct version. I do not see why it can't resolve it. It is working fine locally and in CI:

```
Updated https://github.com/google/flatbuffers.git (0.61s)
Computing version for https://github.com/google/flatbuffers.git
Computed https://github.com/google/flatbuffers.git at 24.3.25 (0.03s)
```

**Comment by timroering** [comment]
Okay after a restart and package cache reset, it works. Thanks for your help.
