### ISSUE TITLE
uv_index_max and uv_index_clear_sky_max missing in weather_api.fbs?

### ISSUE THREAD

**Issue by Danfro** [open-meteo/sdk#148]
Hi, 

I am trying to grab uv index data for day forecast. According to the [api docs](https://open-meteo.com/en/docs) for "Daily Parameter Definition" I need to use `uv_index_max`. But those values are not defined in https://github.com/open-meteo/sdk/blob/main/flatbuffers/weather_api.fbs.

When trying to use it, I get an api error (`'Variable_uv_index_max' is not a member of 'openmeteo_sdk'`). When using `uv_index` the request ends up with a `bad request` error.

Am I doing something wrong? Or would `uv_index_max` and `uv_index_clear_sky_max` need to be added to `weather_api.fbs`?

For reference and in case it helps answering my question, here is the [link to my MR](https://gitlab.com/ubports/development/apps/lomiri-weather-app/-/merge_requests/125).

**Comment by patrick-zippenfenig** [comment]
Hi,
The API request expects `uv_index_max` and `uv_index_clear_sky_max` in the daily weather variables list.

The FlatBuffers response returns `uv_index` or `uv_index_clear_sky` with aggregation set to `max`. Does this help?

**Comment by Danfro** [comment]
Ah, I think I got it. I tried to directly use the max value. With your hint I saw how the aggregation_max is used for another value and adapted that to uv index. Now it works without changing the flatbuffer file.

We can close this issue now as solved, it was my faulty implementation. Thanks for your quick reply!
