### ISSUE TITLE
iOS Versioning issue in Swift 

### ISSUE THREAD

**Issue by chanhihi** [open-meteo/sdk#65]
![image](https://github.com/open-meteo/sdk/assets/85754295/885ea657-cf77-45d1-a730-85d6f552d312)

You can fix it with one more line on line 14.
`@available(iOS 13.0.0, *)`

**Comment by patrick-zippenfenig** [comment]
Would you like to open a PR?

**Comment by chanhihi** [comment]
I'd like to try it, but how do I do it?

**Comment by patrick-zippenfenig** [comment]
Thanks!
