### ISSUE TITLE
New release of the Java SDK

### ISSUE THREAD

**Issue by obones** [open-meteo/sdk#69]
Hello,

I'm writing an openHAB binding for Open-Meteo and as such am using the Java SDK that you provided.
I was about to write an issue about a missing variable value for `sunshine_duration` but as it turns out, the public version on Maven central is from 4 months ago, before the latest changes on the SDK.
Most notably, `sunshine_duration` was added 2 months ago which explains why it's missing.

Would it be possible to update the package at Maven central? Or is there another location to get it from?

Thanks for your help

**Comment by patrick-zippenfenig** [comment]
Hi, currently there is no semantic release publishing for the Java/Kotlin component. At the time I setup the CI integration automatic uploads to the "new" maven central were not support. I just checked and it now seems to be possible by [third party plugins](https://central.sonatype.org/publish/publish-portal-gradle/). I will try to fix the release system next week

**Comment by patrick-zippenfenig** [comment]
I tried the new build plugin. After an hour I gave up and published `1.10.0` manually on maven central.

**Comment by obones** [comment]
Thanks a lot for the time you spent on this, very much appreciated
